
#macro INFOBOX_BASE_WIDTH sprite_get_width(sInfobox)
#macro INFOBOX_BASE_HEIGHT sprite_get_height(sInfobox)


#macro GUI_INFOBOX_WIDTH VIEW_WIDTH * 0.15
#macro GUI_INFOBOX_HEIGHT  INFOBOX_BASE_HEIGHT * GUI_INFOBOX_WIDTH/INFOBOX_BASE_WIDTH

#macro INFOBOX_NAME_X_OFFSET 18
#macro INFOBOX_NAME_Y_OFFSET 10
#macro INFOBOX_NAME_WIDTH 92
#macro INFOBOX_NAME_HEIGHT 24

#macro INFOBOX_DESC_X_OFFSET 10
#macro INFOBOX_DESC_Y_OFFSET 42
#macro INFOBOX_DESC_WIDTH 108
#macro INFOBOX_DESC_HEIGFHT 72



