#macro VIEW_WIDTH 1600//1280//1280//1440 16//(view_get_wport(view_camera[0]))
#macro VIEW_HEIGHT 900//720//720 //9(view_get_hport(view_camera[0]))
#macro CAMERA_WIDTH_RATIO 16
#macro CAMERA_HEIGHT_RATIO 9

#macro CAMERA_SMALLEST_FACTOR 8

#macro VIEW_SIZE_RATIO VIEW_WIDTH / CAMERA_WIDTH_RATIO

#macro ROOM_W 640
#macro ROOM_H 360
#macro GUI_X_SCALE 0.5
#macro GUI_Y_SCALE 0.5

// GAMEPLAY MACROS
enum MOVE_TYPE{
	LINEAR,
	EASE_IN,
	EASE_OUT,
	EASE_IN_OUT,
	EASE_OUT_ELASTIC
}

enum STEP_PRIOTITY{
	PRESTEP,
	PLAYER,
	MOVE,
	ATTACK,
	STEP,
	POSTSTEP,
	COUNT
}

//GUI
#macro GUI_INVENTORY_MAX_HEIGHT VIEW_HEIGHT * 0.85
#macro GUI_INVENTORY_MAX_WIDTH VIEW_WIDTH * 0.8
#macro GUI_COMMAND_WIDTH VIEW_WIDTH * 0.8
#macro GUI_HIDDEN_INVENTORY_MAX_HEIGHT (GUI_MAP_BOT_MARGIN)

#macro GUI_COMMAND_MAX_HEIGHT ((GUI_HIDDEN_INVENTORY_MAX_HEIGHT)*0.8)
#macro GUI_COMMAND_MAX_WIDTH (GUI_COMMAND_WIDTH*0.75)

#macro GUI_INVENTORY_LEFTX 0
#macro GUI_INVENTORY_HIDDEN_Y (VIEW_HEIGHT-GUI_HIDDEN_INVENTORY_MAX_HEIGHT)
#macro GUI_INVENTORY_SHOWN_Y (VIEW_HEIGHT-GUI_INVENTORY_MAX_HEIGHT)

#macro GUI_INVENTORY_NODE_MAX_HEIGHT GUI_INVENTORY_MAX_HEIGHT - GUI_HIDDEN_INVENTORY_MAX_HEIGHT

#macro GUI_INVENTORY_COMMAND_NODE_WIDTH (GUI_COMMAND_MAX_WIDTH)